// Original reusable ad briefs. Placeholders are filled in the library editor.
const briefs = [
  ['ugc-hook-demo', 'UGC: hook → demo → CTA', 'An adult creator films a casual front-camera video in a bright apartment. 0–3s: close-up, the creator holds [product] beside their face and says the hook directly to camera. 3–10s: one clean cut to hands demonstrating the product; show [benefit] through one clear action. 10–15s: return to the creator for the call to action.'],
  ['ugc-problem-solution', 'UGC: problem → solution', 'An adult creator films a handheld phone video at home. 0–4s: show the everyday frustration [problem] with a small, natural reaction. 4–11s: introduce [product] and demonstrate how it helps with [benefit]. 11–15s: creator looks directly at the camera for the call to action. Keep the problem believable and the demonstration easy to follow.'],
  ['ugc-unboxing', 'UGC: unboxing & first look', 'An adult creator unboxes [product] on a tidy kitchen table. 0–3s: overhead hands open the package. 3–8s: close-up reveal, realistic paper and packaging sounds. 8–12s: show the product in use and [benefit]. 12–15s: creator smiles naturally and delivers the call to action. Match package appearance to the attached product image.'],
  ['ugc-routine', 'UGC: everyday routine', 'An adult creator includes [product] in a realistic morning routine. 0–4s: establish a sunlit bathroom or kitchen with one everyday action. 4–11s: a close-up demonstrates the product and [benefit], with normal human pace and accurate hand contact. 11–15s: relaxed medium shot, creator gives the call to action. Feel like a personal phone diary.'],
  ['ugc-creator-story', 'UGC: creator story', 'An adult actor plays a creator explaining [product] in a conversational phone video. 0–5s: eye-level medium close-up, conversational hook. 5–11s: show one product feature that supports [benefit]. 11–15s: end with the call to action and the product visible. Use only the supplied script; do not invent purchase history or additional personal claims.'],
  ['ugc-three-features', 'UGC: three feature cuts', 'A friendly adult creator presents [product]. 0–3s: front-camera hook. 3–6s: macro view of [feature_one]. 6–9s: clear demonstration of [feature_two]. 9–12s: demonstrate [feature_three]. 12–15s: front-camera call to action. Each cut has one distinct purpose and the same product identity.'],
  ['ugc-faceless', 'UGC: faceless hands-on demo', 'Faceless phone-shot product demonstration of [product] on a clean desk. 0–3s: hands bring the product into frame. 3–10s: demonstrate [benefit] through a single clear action. 10–15s: a satisfying detail shot followed by a clean product hero composition. Human hands move naturally; show realistic scale and contact. Use voiceover rather than an on-screen talking person.'],
  ['ugc-founder', 'Ad: founder explains the product', 'An adult actor plays a brand spokesperson in a modest workspace. 0–4s: eye-level close-up with [product] visible in the foreground. 4–11s: explain [benefit] while showing one concrete product detail. 11–15s: finish with a direct call to action. Warm confident delivery, relaxed posture, natural eye contact, no exaggerated acting.'],
  ['ad-product-hero', 'Ad: cinematic product reveal', 'Premium product advertisement for [product]. 0–4s: macro detail emerges from soft shadow. 4–10s: a controlled slow orbit reveals the exact product silhouette and texture from the reference image. 10–15s: end on a stable hero shot with room above the product for later caption editing. Communicate [benefit] visually. Restrained camera motion, realistic materials, polished studio lighting.'],
  ['ad-lifestyle', 'Ad: product in real life', 'Lifestyle advertisement for [product], set in [setting]. 0–4s: a warm establishing shot of an adult using the space. 4–11s: medium shot and one detail cut show the product used naturally, illustrating [benefit]. 11–15s: steady final composition with the product clearly visible. Natural light, believable physical motion, continuity across cuts.'],
  ['ad-faq', 'UGC: answer one objection', 'An adult creator answers the question [question] about [product] in a casual phone video. 0–4s: ask the question with natural curiosity. 4–11s: demonstrate the supplied answer [answer] using the product. 11–15s: end with a calm call to action. Show only the provided features and claims, with realistic scale and timing.'],
  ['ad-offer', 'Ad: offer & CTA', 'Short direct-response advertisement for [product]. 0–3s: a clear attention-grabbing product close-up. 3–10s: show [benefit] in use. 10–15s: an adult presenter delivers the exact offer [offer] and call to action. Keep the product visible and the background simple. Leave clear lower-third space for captions added later.'],
  ['ugc-apparel', 'UGC: outfit & fabric detail', 'An adult creator presents [product] as a casual outfit video in front of a bedroom mirror. 0–4s: full outfit reveal. 4–10s: close-up of the garment fabric and fit, illustrating [benefit]. 10–15s: one natural half-turn and a spoken call to action. Preserve garment color, seams and silhouette from the reference image across shots.'],
  ['ugc-beauty', 'UGC: beauty product application', 'An adult creator demonstrates [product] in a naturally lit bathroom. 0–3s: product held near the camera. 3–11s: show a small amount of the product and one realistic application step, illustrating [benefit]. 11–15s: relaxed close-up and call to action. Natural skin texture and consistent appearance; no instant dramatic transformation.'],
  ['ugc-food', 'UGC: food & drink close-ups', 'An adult creator prepares or serves [product] in a home kitchen. 0–3s: inviting ingredient or packaging reveal. 3–11s: close-up of pouring, mixing or plating, showing [benefit] with accurate liquid and food physics. 11–15s: finished product hero shot and a spoken call to action. Warm daylight, crisp detail, natural kitchen ambience.'],
  ['ugc-desk', 'UGC: desk accessory demonstration', 'An adult creator demonstrates [product] at a home-office desk. 0–4s: show the everyday desk frustration [problem]. 4–11s: one clear hands-on demonstration shows [benefit]. 11–15s: neat final desk composition and call to action. Realistic screen reflections, sensible object scale, accurate hand placement.'],
] as const;

export const UGC_PROMPTS = briefs.map(([id, title, brief]) => ({
  id: `starter-${id}`, title, category: 'UGC / Ads', kind: 'video' as const,
  author: 'Studio original template', modelId: undefined,
  params: { duration: 15, resolution: '720p', aspect_ratio: '9:16', generate_audio: true },
  prompt: `${brief}\n\nFORMAT: 15-second vertical 9:16 video. Product identity must match the uploaded reference image throughout. Smartphone-style realism for creator shots; natural gestures, subtle handheld movement, consistent face and clothing, clean cuts, no watermark, no generated captions or invented logos.\n\nAUDIO: Natural Lithuanian speech, accurate lip sync for talking shots, or Lithuanian voiceover for faceless shots. Exact spoken script: "[spoken_script]". Keep the script short enough for 15 seconds. End with: "[cta]". No added claims or dialogue.`,
  requiresReference: true,
}));
